import { create } from 'zustand';

// Types
export type AppCategory =
  | 'revenue_management'
  | 'channel_management'
  | 'guest_experience'
  | 'upselling'
  | 'guest_messaging'
  | 'digital_keys'
  | 'payments'
  | 'business_intelligence'
  | 'crm_marketing'
  | 'housekeeping'
  | 'fb_pos'
  | 'reputation'
  | 'staff_management'
  | 'accounting'
  | 'security'
  | 'spa_activities'
  | 'parking'
  | 'in_room_tech';

export type AppPricing = 'free' | 'freemium' | 'paid' | 'custom';
export type AppStatus = 'not_installed' | 'installed' | 'pending' | 'needs_update' | 'error';
export type IntegrationType = 'one_click' | 'api' | 'custom' | 'partner';

export interface MarketplaceApp {
  id: string;
  name: string;
  slug: string;
  logo: string;
  shortDescription: string;
  fullDescription: string;
  category: AppCategory;
  subcategory?: string;
  pricing: AppPricing;
  priceRange?: string;
  rating: number;
  reviewCount: number;
  installCount: number;
  status: AppStatus;
  integrationType: IntegrationType;
  isCertified: boolean;
  isFeatured: boolean;
  isNew: boolean;
  isPopular: boolean;
  vendor: {
    name: string;
    website: string;
    supportEmail: string;
  };
  features: string[];
  screenshots: string[];
  integrationCapabilities: string[];
  lastUpdated: string;
  releaseDate: string;
  version: string;
  // For installed apps
  installedAt?: string;
  configuredBy?: string;
  monthlySpend?: number;
  apiCalls?: number;
  healthStatus?: 'healthy' | 'warning' | 'error';
  lastSync?: string;
}

export interface CategoryInfo {
  id: AppCategory;
  name: string;
  description: string;
  icon: string;
  appCount: number;
  color: string;
}

export interface MarketplaceInsight {
  id: string;
  type: 'recommendation' | 'opportunity' | 'alert' | 'optimization' | 'trend';
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  action: string;
  relatedAppId?: string;
  relatedCategory?: AppCategory;
  potentialImpact?: string;
  createdAt: string;
  dismissed: boolean;
}

interface MarketplaceState {
  // Data
  apps: MarketplaceApp[];
  categories: CategoryInfo[];
  insights: MarketplaceInsight[];

  // UI State
  selectedCategory: AppCategory | 'all';
  searchQuery: string;
  sortBy: 'popular' | 'rating' | 'newest' | 'name';
  filterStatus: AppStatus | 'all';
  filterPricing: AppPricing | 'all';

  // Stats
  totalInstalled: number;
  totalMonthlySpend: number;
  totalApiCalls: number;

  // Actions
  setSelectedCategory: (category: AppCategory | 'all') => void;
  setSearchQuery: (query: string) => void;
  setSortBy: (sort: 'popular' | 'rating' | 'newest' | 'name') => void;
  setFilterStatus: (status: AppStatus | 'all') => void;
  setFilterPricing: (pricing: AppPricing | 'all') => void;
  installApp: (appId: string) => void;
  uninstallApp: (appId: string) => void;
  dismissInsight: (insightId: string) => void;
}

// Category definitions (appCount will be calculated dynamically)
const categoryDefinitions: Omit<CategoryInfo, 'appCount'>[] = [
  { id: 'revenue_management', name: 'Revenue Management', description: 'Optimize pricing and maximize RevPAR with AI-powered rate recommendations', icon: 'TrendingUp', color: 'emerald' },
  { id: 'channel_management', name: 'Channel Management', description: 'Distribute inventory across OTAs and booking channels', icon: 'Globe', color: 'blue' },
  { id: 'guest_experience', name: 'Guest Experience', description: 'Enhance guest journeys from booking to checkout', icon: 'Heart', color: 'pink' },
  { id: 'upselling', name: 'Upselling & Ancillary', description: 'Increase revenue with personalized upgrade offers', icon: 'ArrowUpRight', color: 'amber' },
  { id: 'guest_messaging', name: 'Guest Messaging', description: 'Communicate with guests via SMS, WhatsApp, and chat', icon: 'MessageSquare', color: 'violet' },
  { id: 'digital_keys', name: 'Digital Keys & Access', description: 'Mobile keys and contactless room access', icon: 'Key', color: 'cyan' },
  { id: 'payments', name: 'Payments & Billing', description: 'Payment processing and automated billing', icon: 'CreditCard', color: 'green' },
  { id: 'business_intelligence', name: 'Business Intelligence', description: 'Analytics, reporting, and competitive insights', icon: 'BarChart3', color: 'indigo' },
  { id: 'crm_marketing', name: 'CRM & Marketing', description: 'Guest profiles, campaigns, and loyalty programs', icon: 'Users', color: 'purple' },
  { id: 'housekeeping', name: 'Housekeeping & Ops', description: 'Room management, task assignment, and inspection', icon: 'Sparkles', color: 'teal' },
  { id: 'fb_pos', name: 'F&B & POS', description: 'Restaurant, bar, and room service management', icon: 'Utensils', color: 'orange' },
  { id: 'reputation', name: 'Reputation Management', description: 'Reviews, surveys, and sentiment analysis', icon: 'Star', color: 'yellow' },
  { id: 'staff_management', name: 'Staff Management', description: 'Scheduling, communication, and HR tools', icon: 'UserCog', color: 'slate' },
  { id: 'accounting', name: 'Accounting & Finance', description: 'Financial reporting and integrations', icon: 'Calculator', color: 'gray' },
  { id: 'security', name: 'Security & Fraud', description: 'Fraud prevention and cybersecurity', icon: 'Shield', color: 'red' },
  { id: 'spa_activities', name: 'Spa & Activities', description: 'Spa bookings, tours, and experiences', icon: 'Gem', color: 'rose' },
  { id: 'parking', name: 'Parking & Transport', description: 'Parking management and valet services', icon: 'Car', color: 'sky' },
  { id: 'in_room_tech', name: 'In-Room Technology', description: 'Smart TV, voice assistants, and IoT devices', icon: 'Tv', color: 'fuchsia' },
];

// Calculate categories with actual app counts
const getCategoriesWithCounts = (apps: MarketplaceApp[]): CategoryInfo[] => {
  return categoryDefinitions.map(cat => ({
    ...cat,
    appCount: apps.filter(app => app.category === cat.id).length,
  }));
};

// Generate sample marketplace apps
const generateApps = (): MarketplaceApp[] => {
  const apps: MarketplaceApp[] = [
    // Revenue Management
    {
      id: 'ideas-g3',
      name: 'IDeaS G3 RMS',
      slug: 'ideas-g3',
      logo: 'https://www.ideas.com/wp-content/uploads/2023/10/ideas-logo-white.png',
      shortDescription: 'AI-powered revenue management with automated pricing decisions',
      fullDescription: 'IDeaS G3 RMS is the world\'s leading revenue management system, trusted by over 30,000 properties globally. Using advanced machine learning, G3 automates pricing decisions across all room types and market segments.',
      category: 'revenue_management',
      pricing: 'custom',
      priceRange: '¥200,000 - ¥500,000/month',
      rating: 4.8,
      reviewCount: 342,
      installCount: 2840,
      status: 'installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'IDeaS Revenue Solutions', website: 'https://ideas.com', supportEmail: 'support@ideas.com' },
      features: ['Automated pricing', 'Demand forecasting', 'Group pricing', 'Function space optimization', 'What-if analysis'],
      screenshots: [],
      integrationCapabilities: ['Real-time rate updates', 'Bi-directional sync', 'Multi-property support'],
      lastUpdated: '2025-01-15',
      releaseDate: '2018-03-01',
      version: '3.2.1',
      installedAt: '2024-06-15',
      configuredBy: 'Tanaka Yuki',
      monthlySpend: 280000,
      apiCalls: 45000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:30:00Z',
    },
    {
      id: 'duetto',
      name: 'Duetto GameChanger',
      slug: 'duetto',
      logo: 'https://duettocloud.com/wp-content/uploads/2021/03/duetto-logo-white.svg',
      shortDescription: 'Open pricing platform for casino resorts and hotels',
      fullDescription: 'Duetto delivers a powerful suite of cloud-based revenue strategy solutions that address the unique business needs of casino resorts, luxury properties, and hotel groups.',
      category: 'revenue_management',
      pricing: 'custom',
      priceRange: '¥150,000 - ¥400,000/month',
      rating: 4.7,
      reviewCount: 218,
      installCount: 1520,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Duetto', website: 'https://duettocloud.com', supportEmail: 'support@duetto.com' },
      features: ['Open pricing', 'Casino integration', 'Real-time analytics', 'Forecasting'],
      screenshots: [],
      integrationCapabilities: ['Real-time sync', 'Casino loyalty integration'],
      lastUpdated: '2025-01-10',
      releaseDate: '2019-06-01',
      version: '4.1.0',
    },
    {
      id: 'atomize',
      name: 'Atomize RMS',
      slug: 'atomize',
      logo: '',
      shortDescription: 'Automated revenue management for independent hotels',
      fullDescription: 'Atomize is the leading revenue management system for independent hotels and small chains. Fully automated pricing recommendations updated 24/7.',
      category: 'revenue_management',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥120,000/month',
      rating: 4.6,
      reviewCount: 156,
      installCount: 890,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Atomize', website: 'https://atomize.com', supportEmail: 'hello@atomize.com' },
      features: ['Auto-pricing', 'Easy setup', 'Multi-property', 'Mobile app'],
      screenshots: [],
      integrationCapabilities: ['One-click setup', 'Automatic rate push'],
      lastUpdated: '2024-12-20',
      releaseDate: '2020-01-15',
      version: '2.8.3',
    },

    // Channel Management
    {
      id: 'siteminder',
      name: 'SiteMinder',
      slug: 'siteminder',
      logo: 'https://companieslogo.com/img/orig/SDR.AX_BIG-1a8882a6.png',
      shortDescription: 'World\'s leading hotel channel manager',
      fullDescription: 'SiteMinder is the world\'s largest open hotel commerce platform, connecting hotels to over 450 distribution channels including Booking.com, Expedia, and Airbnb.',
      category: 'channel_management',
      pricing: 'paid',
      priceRange: '¥30,000 - ¥80,000/month',
      rating: 4.7,
      reviewCount: 892,
      installCount: 5200,
      status: 'installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'SiteMinder', website: 'https://siteminder.com', supportEmail: 'support@siteminder.com' },
      features: ['450+ channels', 'Rate parity', 'Metasearch', 'Booking engine'],
      screenshots: [],
      integrationCapabilities: ['Real-time inventory sync', 'Two-way messaging'],
      lastUpdated: '2025-01-18',
      releaseDate: '2015-01-01',
      version: '5.4.2',
      installedAt: '2023-03-10',
      configuredBy: 'System Admin',
      monthlySpend: 55000,
      apiCalls: 125000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:45:00Z',
    },

    // Guest Experience
    {
      id: 'duve',
      name: 'Duve',
      slug: 'duve',
      logo: 'https://cdn.brandfetch.io/id5IE6946i/w/820/h/235/theme/dark/logo.png',
      shortDescription: 'Unified guest experience platform with AI',
      fullDescription: 'Duve is a leading guest experience platform that unifies communication, upselling, and operations. Recently raised $60M to scale AI-driven personalization.',
      category: 'guest_experience',
      pricing: 'paid',
      priceRange: '¥80,000 - ¥200,000/month',
      rating: 4.9,
      reviewCount: 445,
      installCount: 3100,
      status: 'installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Duve', website: 'https://duve.com', supportEmail: 'support@duve.com' },
      features: ['Guest app', 'Digital check-in', 'Upselling', 'Unified inbox', 'AI concierge'],
      screenshots: [],
      integrationCapabilities: ['Deep PMS integration', 'Payment processing', 'Door lock systems'],
      lastUpdated: '2025-01-19',
      releaseDate: '2019-08-01',
      version: '6.2.0',
      installedAt: '2024-01-20',
      configuredBy: 'Tanaka Yuki',
      monthlySpend: 120000,
      apiCalls: 89000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:50:00Z',
    },
    {
      id: 'canary',
      name: 'Canary Technologies',
      slug: 'canary',
      logo: '',
      shortDescription: 'Contactless check-in, checkout, and fraud prevention',
      fullDescription: 'Canary provides hotels with contactless solutions including digital check-in, checkout, tipping, and industry-leading fraud prevention.',
      category: 'guest_experience',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.8,
      reviewCount: 567,
      installCount: 4200,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Canary Technologies', website: 'https://canarytechnologies.com', supportEmail: 'support@canary.com' },
      features: ['Digital check-in', 'Digital checkout', 'Digital tipping', 'Fraud prevention', 'Upselling'],
      screenshots: [],
      integrationCapabilities: ['Seamless PMS sync', 'Payment integration'],
      lastUpdated: '2025-01-17',
      releaseDate: '2018-05-01',
      version: '4.5.1',
    },

    // Upselling
    {
      id: 'oaky',
      name: 'Oaky',
      slug: 'oaky',
      logo: '',
      shortDescription: 'Hyper-personalized upselling automation',
      fullDescription: 'Oaky helps hotels increase revenue through automated, personalized upselling across the entire guest journey. Average 8-15% revenue uplift.',
      category: 'upselling',
      pricing: 'paid',
      priceRange: '¥60,000 - ¥150,000/month',
      rating: 4.7,
      reviewCount: 289,
      installCount: 1850,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Oaky', website: 'https://oaky.com', supportEmail: 'support@oaky.com' },
      features: ['Pre-arrival upsell', 'Room upgrades', 'F&B packages', 'Experiences', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Payment processing', 'CRM sync'],
      lastUpdated: '2025-01-14',
      releaseDate: '2017-09-01',
      version: '3.8.0',
    },

    // Guest Messaging
    {
      id: 'akia',
      name: 'Akia',
      slug: 'akia',
      logo: '',
      shortDescription: 'AI-powered guest messaging and automation',
      fullDescription: 'Akia is an AI-first guest messaging platform that automates 70% of guest inquiries while delivering personalized experiences at scale.',
      category: 'guest_messaging',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥120,000/month',
      rating: 4.8,
      reviewCount: 198,
      installCount: 1200,
      status: 'installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: true,
      isNew: true,
      isPopular: true,
      vendor: { name: 'Akia', website: 'https://akia.com', supportEmail: 'hello@akia.com' },
      features: ['AI chatbot', 'SMS/WhatsApp', 'Automated responses', 'Staff handoff', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['Multi-channel messaging', 'PMS sync', 'Task creation'],
      lastUpdated: '2025-01-20',
      releaseDate: '2021-03-01',
      version: '2.4.0',
      installedAt: '2024-09-15',
      configuredBy: 'Front Desk Manager',
      monthlySpend: 75000,
      apiCalls: 32000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:55:00Z',
    },

    // Digital Keys
    {
      id: 'assa-abloy',
      name: 'ASSA ABLOY Mobile Access',
      slug: 'assa-abloy',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/ASSA_ABLOY_logo.svg/320px-ASSA_ABLOY_logo.svg.png',
      shortDescription: 'Industry-leading mobile key solution',
      fullDescription: 'ASSA ABLOY Mobile Access enables guests to use their smartphones as room keys, providing seamless contactless access.',
      category: 'digital_keys',
      pricing: 'custom',
      priceRange: 'Contact for pricing',
      rating: 4.6,
      reviewCount: 234,
      installCount: 2100,
      status: 'installed',
      integrationType: 'custom',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'ASSA ABLOY', website: 'https://assaabloy.com', supportEmail: 'hospitality@assaabloy.com' },
      features: ['Mobile key', 'BLE technology', 'Staff access', 'Audit trail'],
      screenshots: [],
      integrationCapabilities: ['Deep PMS integration', 'Guest app SDK'],
      lastUpdated: '2024-11-15',
      releaseDate: '2016-01-01',
      version: '5.1.0',
      installedAt: '2022-08-01',
      configuredBy: 'IT Department',
      monthlySpend: 45000,
      apiCalls: 28000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:40:00Z',
    },

    // Payments
    {
      id: 'stripe',
      name: 'Stripe',
      slug: 'stripe',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Stripe_Logo%2C_revised_2016.svg/320px-Stripe_Logo%2C_revised_2016.svg.png',
      shortDescription: 'Global payment processing for hospitality',
      fullDescription: 'Stripe provides payment infrastructure for hotels, supporting 135+ currencies and dozens of payment methods including credit cards, digital wallets, and local payment methods.',
      category: 'payments',
      pricing: 'paid',
      priceRange: '3.6% + ¥30 per transaction',
      rating: 4.9,
      reviewCount: 1245,
      installCount: 8900,
      status: 'installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Stripe', website: 'https://stripe.com', supportEmail: 'support@stripe.com' },
      features: ['Global payments', '135+ currencies', 'Fraud prevention', 'Subscriptions', 'Invoicing'],
      screenshots: [],
      integrationCapabilities: ['PMS payment sync', 'Automated reconciliation'],
      lastUpdated: '2025-01-20',
      releaseDate: '2015-01-01',
      version: 'API v2024-12',
      installedAt: '2021-01-01',
      configuredBy: 'Finance Manager',
      monthlySpend: 0, // Transaction-based
      apiCalls: 15000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T15:00:00Z',
    },

    // Business Intelligence
    {
      id: 'ota-insight',
      name: 'OTA Insight',
      slug: 'ota-insight',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Ota-insight-logo.jpg/320px-Ota-insight-logo.jpg',
      shortDescription: 'Market intelligence and rate shopping',
      fullDescription: 'OTA Insight provides cloud-based business intelligence solutions including rate intelligence, parity insight, and revenue insight for hotels worldwide.',
      category: 'business_intelligence',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.7,
      reviewCount: 456,
      installCount: 3400,
      status: 'installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'OTA Insight', website: 'https://otainsight.com', supportEmail: 'support@otainsight.com' },
      features: ['Rate shopping', 'Parity monitoring', 'Market analysis', 'Demand calendar'],
      screenshots: [],
      integrationCapabilities: ['Automated data sync', 'API access'],
      lastUpdated: '2025-01-16',
      releaseDate: '2017-06-01',
      version: '3.2.0',
      installedAt: '2024-02-01',
      configuredBy: 'Revenue Manager',
      monthlySpend: 65000,
      apiCalls: 12000,
      healthStatus: 'healthy',
      lastSync: '2025-01-20T14:35:00Z',
    },

    // Housekeeping
    {
      id: 'optii',
      name: 'Optii Solutions',
      slug: 'optii',
      logo: '',
      shortDescription: 'AI-powered housekeeping optimization',
      fullDescription: 'Optii uses AI to optimize housekeeping operations, reducing costs while improving guest satisfaction through smart room assignment and predictive scheduling.',
      category: 'housekeeping',
      pricing: 'paid',
      priceRange: '¥30,000 - ¥80,000/month',
      rating: 4.6,
      reviewCount: 178,
      installCount: 950,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Optii Solutions', website: 'https://optii.com', supportEmail: 'support@optii.com' },
      features: ['AI scheduling', 'Real-time tracking', 'Job dispatch', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS room status sync', 'Task management'],
      lastUpdated: '2024-12-10',
      releaseDate: '2019-04-01',
      version: '2.9.0',
    },
    {
      id: 'flexkeeping',
      name: 'Flexkeeping',
      slug: 'flexkeeping',
      logo: '',
      shortDescription: 'Hotel operations and housekeeping platform',
      fullDescription: 'Flexkeeping streamlines hotel operations with real-time communication, task management, and housekeeping optimization.',
      category: 'housekeeping',
      pricing: 'paid',
      priceRange: '¥25,000 - ¥60,000/month',
      rating: 4.5,
      reviewCount: 145,
      installCount: 720,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: false,
      vendor: { name: 'Flexkeeping', website: 'https://flexkeeping.com', supportEmail: 'support@flexkeeping.com' },
      features: ['Task management', 'Team chat', 'Inspections', 'Lost & found'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Mobile app'],
      lastUpdated: '2024-11-20',
      releaseDate: '2018-07-01',
      version: '4.2.1',
    },

    // Reputation
    {
      id: 'trustyou',
      name: 'TrustYou',
      slug: 'trustyou',
      logo: '',
      shortDescription: 'Guest feedback and reputation management',
      fullDescription: 'TrustYou helps hotels collect, analyze, and act on guest feedback across all channels. Comprehensive reputation management with AI-powered sentiment analysis.',
      category: 'reputation',
      pricing: 'paid',
      priceRange: '¥35,000 - ¥90,000/month',
      rating: 4.6,
      reviewCount: 312,
      installCount: 2100,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'TrustYou', website: 'https://trustyou.com', supportEmail: 'support@trustyou.com' },
      features: ['Review aggregation', 'Survey builder', 'Sentiment analysis', 'Competitive benchmarking'],
      screenshots: [],
      integrationCapabilities: ['Multi-platform sync', 'Automated surveys'],
      lastUpdated: '2025-01-12',
      releaseDate: '2016-01-01',
      version: '5.0.0',
    },

    // F&B
    {
      id: 'lightspeed',
      name: 'Lightspeed Restaurant',
      slug: 'lightspeed',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Lightspeed_logo.svg/320px-Lightspeed_logo.svg.png',
      shortDescription: 'All-in-one restaurant POS for hotels',
      fullDescription: 'Lightspeed Restaurant is a cloud-based POS system designed for hotel restaurants, bars, and room service with seamless PMS integration.',
      category: 'fb_pos',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.5,
      reviewCount: 567,
      installCount: 3200,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Lightspeed', website: 'https://lightspeedhq.com', supportEmail: 'support@lightspeed.com' },
      features: ['Table management', 'Room charges', 'Kitchen display', 'Inventory', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS charge posting', 'Payment integration'],
      lastUpdated: '2025-01-08',
      releaseDate: '2017-03-01',
      version: '6.1.0',
    },

    // CRM & Marketing
    {
      id: 'revinate',
      name: 'Revinate',
      slug: 'revinate',
      logo: '',
      shortDescription: 'Hotel CRM and marketing automation',
      fullDescription: 'Revinate is the leading hotel CRM platform, helping hotels build direct relationships with guests through email marketing, guest feedback, and reputation management.',
      category: 'crm_marketing',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥150,000/month',
      rating: 4.7,
      reviewCount: 423,
      installCount: 2800,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Revinate', website: 'https://revinate.com', supportEmail: 'support@revinate.com' },
      features: ['Guest CRM', 'Email marketing', 'Surveys', 'Reputation', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS guest sync', 'Marketing automation'],
      lastUpdated: '2025-01-15',
      releaseDate: '2015-06-01',
      version: '7.2.0',
    },

    // Security
    {
      id: 'sertifi',
      name: 'Sertifi',
      slug: 'sertifi',
      logo: '',
      shortDescription: 'E-signatures and payment authorization',
      fullDescription: 'Sertifi provides e-signature and payment authorization solutions designed specifically for the hospitality industry, reducing fraud and accelerating bookings.',
      category: 'security',
      pricing: 'paid',
      priceRange: '¥30,000 - ¥80,000/month',
      rating: 4.6,
      reviewCount: 234,
      installCount: 1500,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Sertifi', website: 'https://sertifi.com', supportEmail: 'support@sertifi.com' },
      features: ['E-signatures', 'Payment auth', 'Contract management', 'Audit trail'],
      screenshots: [],
      integrationCapabilities: ['PMS contract sync', 'Sales integration'],
      lastUpdated: '2024-12-01',
      releaseDate: '2014-01-01',
      version: '4.8.0',
    },

    // Spa
    {
      id: 'book4time',
      name: 'Book4Time',
      slug: 'book4time',
      logo: '',
      shortDescription: 'Spa and wellness management platform',
      fullDescription: 'Book4Time is the leading spa and wellness management platform for hotels, providing online booking, staff scheduling, and comprehensive reporting.',
      category: 'spa_activities',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥120,000/month',
      rating: 4.7,
      reviewCount: 189,
      installCount: 1100,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Book4Time', website: 'https://book4time.com', supportEmail: 'support@book4time.com' },
      features: ['Online booking', 'Staff scheduling', 'POS', 'Memberships', 'Gift cards'],
      screenshots: [],
      integrationCapabilities: ['PMS charge posting', 'Guest profile sync'],
      lastUpdated: '2024-12-15',
      releaseDate: '2010-01-01',
      version: '8.0.0',
    },

    // Staff Management
    {
      id: 'hotschedules',
      name: 'HotSchedules',
      slug: 'hotschedules',
      logo: '',
      shortDescription: 'Restaurant and hotel staff scheduling',
      fullDescription: 'HotSchedules is the leading employee scheduling and labor management platform for hospitality, helping optimize labor costs while improving employee satisfaction.',
      category: 'staff_management',
      pricing: 'paid',
      priceRange: '¥20,000 - ¥60,000/month',
      rating: 4.4,
      reviewCount: 678,
      installCount: 4500,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Fourth', website: 'https://fourth.com', supportEmail: 'support@fourth.com' },
      features: ['Scheduling', 'Time & attendance', 'Labor forecasting', 'Mobile app'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Payroll sync'],
      lastUpdated: '2024-11-25',
      releaseDate: '2008-01-01',
      version: '10.2.0',
    },

    // Accounting
    {
      id: 'm3',
      name: 'M3 Accounting',
      slug: 'm3',
      logo: '',
      shortDescription: 'Hotel accounting and financial reporting',
      fullDescription: 'M3 is the hospitality industry\'s leading cloud-based accounting, financial, and data management platform, serving over 7,500 properties.',
      category: 'accounting',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥150,000/month',
      rating: 4.5,
      reviewCount: 234,
      installCount: 1800,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'M3', website: 'https://m3as.com', supportEmail: 'support@m3as.com' },
      features: ['General ledger', 'AP/AR', 'Financial reporting', 'Budgeting', 'Bank reconciliation'],
      screenshots: [],
      integrationCapabilities: ['PMS revenue sync', 'Bank feeds'],
      lastUpdated: '2025-01-05',
      releaseDate: '2005-01-01',
      version: '12.0.0',
    },

    // Additional Revenue Management Apps
    {
      id: 'rainmaker',
      name: 'Rainmaker',
      slug: 'rainmaker',
      logo: '',
      shortDescription: 'Revenue management for casino and resort properties',
      fullDescription: 'Rainmaker provides sophisticated revenue optimization for casino resorts, integrating gaming and non-gaming revenue streams.',
      category: 'revenue_management',
      pricing: 'custom',
      priceRange: '¥180,000 - ¥450,000/month',
      rating: 4.5,
      reviewCount: 123,
      installCount: 680,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: false,
      vendor: { name: 'Rainmaker Group', website: 'https://letitrain.com', supportEmail: 'support@letitrain.com' },
      features: ['Casino integration', 'Group pricing', 'Event optimization', 'Forecasting'],
      screenshots: [],
      integrationCapabilities: ['Gaming system integration', 'Multi-property'],
      lastUpdated: '2024-12-15',
      releaseDate: '2012-06-01',
      version: '8.5.0',
    },
    {
      id: 'revenue-analytics',
      name: 'Revenue Analytics (N2N)',
      slug: 'revenue-analytics',
      logo: '',
      shortDescription: 'Cloud-native revenue optimization platform',
      fullDescription: 'N2N Revenue Analytics combines machine learning with deep hotel industry expertise for accurate demand forecasting and pricing.',
      category: 'revenue_management',
      pricing: 'paid',
      priceRange: '¥80,000 - ¥180,000/month',
      rating: 4.4,
      reviewCount: 89,
      installCount: 520,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: true,
      isPopular: false,
      vendor: { name: 'N2N Services', website: 'https://n2nservices.com', supportEmail: 'hello@n2nservices.com' },
      features: ['ML forecasting', 'Competitive analysis', 'Rate recommendations', 'Dashboard'],
      screenshots: [],
      integrationCapabilities: ['Quick setup', 'API access'],
      lastUpdated: '2025-01-10',
      releaseDate: '2022-03-01',
      version: '2.1.0',
    },

    // Additional Channel Management Apps
    {
      id: 'rategain',
      name: 'RateGain',
      slug: 'rategain',
      logo: '',
      shortDescription: 'AI-powered distribution and rate intelligence',
      fullDescription: 'RateGain offers comprehensive distribution technology including channel management, rate shopping, and digital marketing solutions.',
      category: 'channel_management',
      pricing: 'paid',
      priceRange: '¥35,000 - ¥90,000/month',
      rating: 4.5,
      reviewCount: 345,
      installCount: 2100,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'RateGain', website: 'https://rategain.com', supportEmail: 'support@rategain.com' },
      features: ['Channel manager', 'Rate shopping', 'Parity monitoring', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['350+ OTA connections', 'Real-time sync'],
      lastUpdated: '2025-01-12',
      releaseDate: '2015-01-01',
      version: '6.2.0',
    },
    {
      id: 'dingus',
      name: 'D-EDGE (Dingus)',
      slug: 'dingus',
      logo: '',
      shortDescription: 'Central reservation and distribution platform',
      fullDescription: 'D-EDGE provides a comprehensive hospitality technology ecosystem including CRS, channel management, and digital marketing.',
      category: 'channel_management',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.4,
      reviewCount: 234,
      installCount: 1500,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'D-EDGE', website: 'https://d-edge.com', supportEmail: 'support@d-edge.com' },
      features: ['CRS', 'Channel manager', 'Booking engine', 'Metasearch'],
      screenshots: [],
      integrationCapabilities: ['Full API', 'GDS connectivity'],
      lastUpdated: '2024-11-20',
      releaseDate: '2010-01-01',
      version: '5.8.0',
    },

    // Additional Guest Experience Apps
    {
      id: 'alice',
      name: 'ALICE',
      slug: 'alice',
      logo: '',
      shortDescription: 'Hotel operations platform for guest services',
      fullDescription: 'ALICE connects every department of your hotel with one powerful operations platform, improving staff efficiency and guest satisfaction.',
      category: 'guest_experience',
      pricing: 'paid',
      priceRange: '¥60,000 - ¥150,000/month',
      rating: 4.6,
      reviewCount: 312,
      installCount: 1800,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'ALICE', website: 'https://aliceplatform.com', supportEmail: 'support@alice.com' },
      features: ['Task management', 'Guest requests', 'Staff communication', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Ticketing system'],
      lastUpdated: '2025-01-08',
      releaseDate: '2016-03-01',
      version: '4.5.0',
    },
    {
      id: 'guestware',
      name: 'GuestWare',
      slug: 'guestware',
      logo: '',
      shortDescription: 'Guest recognition and preference management',
      fullDescription: 'GuestWare helps hotels deliver personalized experiences by tracking guest preferences and history across stays and properties.',
      category: 'guest_experience',
      pricing: 'paid',
      priceRange: '¥45,000 - ¥100,000/month',
      rating: 4.5,
      reviewCount: 187,
      installCount: 950,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: false,
      vendor: { name: 'GuestWare', website: 'https://guestware.com', supportEmail: 'support@guestware.com' },
      features: ['Guest profiles', 'Preference tracking', 'VIP recognition', 'Reporting'],
      screenshots: [],
      integrationCapabilities: ['Multi-property sync', 'PMS integration'],
      lastUpdated: '2024-10-15',
      releaseDate: '2008-01-01',
      version: '7.2.0',
    },

    // Additional Upselling Apps
    {
      id: 'nor1',
      name: 'Nor1 (Oracle)',
      slug: 'nor1',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/320px-Oracle_logo.svg.png',
      shortDescription: 'AI-powered upselling and merchandising',
      fullDescription: 'Nor1 uses machine learning to optimize room upgrade offers and ancillary sales throughout the guest journey.',
      category: 'upselling',
      pricing: 'custom',
      priceRange: 'Revenue share model',
      rating: 4.6,
      reviewCount: 245,
      installCount: 1400,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Oracle Hospitality', website: 'https://oracle.com/hospitality', supportEmail: 'hospitality@oracle.com' },
      features: ['Room upgrades', 'Ancillary offers', 'Dynamic pricing', 'A/B testing'],
      screenshots: [],
      integrationCapabilities: ['Deep PMS integration', 'Payment processing'],
      lastUpdated: '2025-01-05',
      releaseDate: '2014-01-01',
      version: '5.0.0',
    },
    {
      id: 'roomraccoon',
      name: 'RoomRaccoon Upsell',
      slug: 'roomraccoon',
      logo: '',
      shortDescription: 'Automated upselling for independent hotels',
      fullDescription: 'RoomRaccoon offers an all-in-one solution with powerful upselling features for boutique and independent properties.',
      category: 'upselling',
      pricing: 'paid',
      priceRange: '¥25,000 - ¥60,000/month',
      rating: 4.4,
      reviewCount: 156,
      installCount: 780,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: true,
      isPopular: false,
      vendor: { name: 'RoomRaccoon', website: 'https://roomraccoon.com', supportEmail: 'support@roomraccoon.com' },
      features: ['Pre-arrival upsells', 'Add-ons', 'Automated emails', 'Guest portal'],
      screenshots: [],
      integrationCapabilities: ['Easy setup', 'Payment integration'],
      lastUpdated: '2025-01-15',
      releaseDate: '2020-06-01',
      version: '3.2.0',
    },

    // Additional Guest Messaging Apps
    {
      id: 'whistle',
      name: 'Whistle (Medallia)',
      slug: 'whistle',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Medallia_logo.svg/320px-Medallia_logo.svg.png',
      shortDescription: 'Unified guest messaging platform',
      fullDescription: 'Whistle enables hotels to communicate with guests through their preferred channels including SMS, WhatsApp, and web chat.',
      category: 'guest_messaging',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥90,000/month',
      rating: 4.7,
      reviewCount: 267,
      installCount: 1600,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Medallia', website: 'https://medallia.com', supportEmail: 'support@medallia.com' },
      features: ['Multi-channel', 'AI responses', 'Translation', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS sync', 'CRM integration'],
      lastUpdated: '2025-01-10',
      releaseDate: '2017-01-01',
      version: '4.8.0',
    },
    {
      id: 'kipsu',
      name: 'Kipsu',
      slug: 'kipsu',
      logo: '',
      shortDescription: 'Real-time guest engagement messaging',
      fullDescription: 'Kipsu helps hotels engage guests in real-time through text messaging, improving service recovery and guest satisfaction.',
      category: 'guest_messaging',
      pricing: 'paid',
      priceRange: '¥35,000 - ¥80,000/month',
      rating: 4.6,
      reviewCount: 198,
      installCount: 1200,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Kipsu', website: 'https://kipsu.com', supportEmail: 'hello@kipsu.com' },
      features: ['SMS messaging', 'Team collaboration', 'Service recovery', 'Reporting'],
      screenshots: [],
      integrationCapabilities: ['Quick setup', 'PMS integration'],
      lastUpdated: '2024-12-20',
      releaseDate: '2015-01-01',
      version: '5.2.0',
    },

    // Additional Digital Keys Apps
    {
      id: 'openkey',
      name: 'OpenKey',
      slug: 'openkey',
      logo: '',
      shortDescription: 'Universal mobile key platform',
      fullDescription: 'OpenKey works with any lock system to provide guests with secure mobile key access through their smartphones.',
      category: 'digital_keys',
      pricing: 'paid',
      priceRange: '¥30,000 - ¥70,000/month',
      rating: 4.5,
      reviewCount: 145,
      installCount: 890,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'OpenKey', website: 'https://openkey.co', supportEmail: 'support@openkey.co' },
      features: ['Mobile keys', 'Lock agnostic', 'Guest app', 'Dashboard'],
      screenshots: [],
      integrationCapabilities: ['Multiple lock vendors', 'PMS sync'],
      lastUpdated: '2024-11-10',
      releaseDate: '2016-01-01',
      version: '4.0.0',
    },
    {
      id: 'salto',
      name: 'SALTO KS',
      slug: 'salto',
      logo: '',
      shortDescription: 'Cloud-based access control system',
      fullDescription: 'SALTO KS provides flexible keyless access solutions for hotels, combining physical and digital credentials.',
      category: 'digital_keys',
      pricing: 'custom',
      priceRange: 'Contact for pricing',
      rating: 4.6,
      reviewCount: 178,
      installCount: 1100,
      status: 'not_installed',
      integrationType: 'custom',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'SALTO Systems', website: 'https://saltosystems.com', supportEmail: 'info@saltosystems.com' },
      features: ['Mobile access', 'PIN codes', 'Audit trail', 'Remote management'],
      screenshots: [],
      integrationCapabilities: ['Cloud platform', 'API access'],
      lastUpdated: '2025-01-02',
      releaseDate: '2018-01-01',
      version: '3.5.0',
    },

    // Additional Payments Apps
    {
      id: 'adyen',
      name: 'Adyen',
      slug: 'adyen',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Adyen_Corporate_Logo.svg/320px-Adyen_Corporate_Logo.svg.png',
      shortDescription: 'Enterprise payment platform for hospitality',
      fullDescription: 'Adyen provides a single payments platform for hotels, supporting in-person, online, and mobile payments globally.',
      category: 'payments',
      pricing: 'paid',
      priceRange: 'Transaction-based pricing',
      rating: 4.8,
      reviewCount: 567,
      installCount: 3200,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Adyen', website: 'https://adyen.com', supportEmail: 'support@adyen.com' },
      features: ['Unified commerce', 'Global payments', 'Fraud prevention', 'Terminals'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Omnichannel'],
      lastUpdated: '2025-01-18',
      releaseDate: '2015-01-01',
      version: 'API v68',
    },
    {
      id: 'mews-payments',
      name: 'Mews Payments',
      slug: 'mews-payments',
      logo: 'https://mews.com/hubfs/mews-logo-dark.svg',
      shortDescription: 'Native payment processing for Mews PMS',
      fullDescription: 'Mews Payments offers seamless payment processing directly integrated with the Mews property management system.',
      category: 'payments',
      pricing: 'paid',
      priceRange: '2.9% + ¥25 per transaction',
      rating: 4.7,
      reviewCount: 234,
      installCount: 1800,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Mews', website: 'https://mews.com', supportEmail: 'support@mews.com' },
      features: ['Native integration', 'Auto reconciliation', 'Multi-currency', 'PCI compliant'],
      screenshots: [],
      integrationCapabilities: ['One-click setup', 'Automatic posting'],
      lastUpdated: '2025-01-12',
      releaseDate: '2019-01-01',
      version: '2.5.0',
    },

    // Additional Business Intelligence Apps
    {
      id: 'hotstats',
      name: 'HotStats',
      slug: 'hotstats',
      logo: '',
      shortDescription: 'Hotel profit and loss benchmarking',
      fullDescription: 'HotStats provides the global hotel industry with monthly profit and loss benchmarking data for accurate performance analysis.',
      category: 'business_intelligence',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥120,000/month',
      rating: 4.7,
      reviewCount: 189,
      installCount: 1400,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'HotStats', website: 'https://hotstats.com', supportEmail: 'info@hotstats.com' },
      features: ['P&L benchmarking', 'GOPPAR analysis', 'Market comparison', 'Trends'],
      screenshots: [],
      integrationCapabilities: ['Data import', 'Custom reports'],
      lastUpdated: '2025-01-05',
      releaseDate: '2010-01-01',
      version: '4.0.0',
    },
    {
      id: 'str',
      name: 'STR (CoStar)',
      slug: 'str',
      logo: 'https://www.str.com/hubfs/STR%20Brand%20Logos/STR%20Logo%202023.png',
      shortDescription: 'Industry-leading hotel market data',
      fullDescription: 'STR provides comprehensive market data and benchmarking for the global hotel industry, including occupancy, ADR, and RevPAR metrics.',
      category: 'business_intelligence',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.8,
      reviewCount: 456,
      installCount: 5200,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'CoStar Group', website: 'https://str.com', supportEmail: 'support@str.com' },
      features: ['Market data', 'Comp sets', 'Trend analysis', 'Forward-looking'],
      screenshots: [],
      integrationCapabilities: ['Data feeds', 'API access'],
      lastUpdated: '2025-01-15',
      releaseDate: '1995-01-01',
      version: 'v2024',
    },

    // Additional CRM & Marketing Apps
    {
      id: 'cendyn',
      name: 'Cendyn CRM',
      slug: 'cendyn',
      logo: '',
      shortDescription: 'Hospitality-focused CRM and marketing',
      fullDescription: 'Cendyn provides integrated CRM and digital marketing solutions specifically designed for the hospitality industry.',
      category: 'crm_marketing',
      pricing: 'paid',
      priceRange: '¥70,000 - ¥180,000/month',
      rating: 4.6,
      reviewCount: 234,
      installCount: 1600,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Cendyn', website: 'https://cendyn.com', supportEmail: 'support@cendyn.com' },
      features: ['Guest CRM', 'Email marketing', 'Loyalty', 'Personalization'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Multi-property'],
      lastUpdated: '2025-01-08',
      releaseDate: '2012-01-01',
      version: '6.0.0',
    },
    {
      id: 'profitroom',
      name: 'Profitroom',
      slug: 'profitroom',
      logo: '',
      shortDescription: 'Direct booking and marketing platform',
      fullDescription: 'Profitroom helps hotels increase direct bookings through a booking engine, CRM, and marketing automation.',
      category: 'crm_marketing',
      pricing: 'paid',
      priceRange: '¥35,000 - ¥80,000/month',
      rating: 4.5,
      reviewCount: 178,
      installCount: 1200,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Profitroom', website: 'https://profitroom.com', supportEmail: 'support@profitroom.com' },
      features: ['Booking engine', 'CRM', 'Marketing automation', 'Website builder'],
      screenshots: [],
      integrationCapabilities: ['Channel manager', 'Payment gateway'],
      lastUpdated: '2024-12-15',
      releaseDate: '2015-01-01',
      version: '4.5.0',
    },

    // Additional F&B & POS Apps
    {
      id: 'infrasys',
      name: 'Infrasys POS',
      slug: 'infrasys',
      logo: '',
      shortDescription: 'Enterprise F&B POS for hotels',
      fullDescription: 'Infrasys provides a comprehensive point of sale solution for hotel food and beverage operations with seamless PMS integration.',
      category: 'fb_pos',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥120,000/month',
      rating: 4.5,
      reviewCount: 234,
      installCount: 1400,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Infrasys', website: 'https://infrasys.net', supportEmail: 'support@infrasys.net' },
      features: ['POS', 'Kitchen display', 'Inventory', 'Room charges'],
      screenshots: [],
      integrationCapabilities: ['PMS charge posting', 'Payment integration'],
      lastUpdated: '2024-11-25',
      releaseDate: '2005-01-01',
      version: '9.2.0',
    },
    {
      id: 'simphony',
      name: 'Oracle Simphony',
      slug: 'simphony',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Oracle_logo.svg/320px-Oracle_logo.svg.png',
      shortDescription: 'Cloud POS for hospitality F&B',
      fullDescription: 'Oracle Simphony is a cloud-based POS platform designed for hotel restaurants, bars, and room service operations.',
      category: 'fb_pos',
      pricing: 'custom',
      priceRange: '¥60,000 - ¥150,000/month',
      rating: 4.6,
      reviewCount: 345,
      installCount: 2800,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Oracle Hospitality', website: 'https://oracle.com/hospitality', supportEmail: 'hospitality@oracle.com' },
      features: ['Cloud POS', 'Kitchen display', 'Labor management', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['OPERA integration', 'Payments'],
      lastUpdated: '2025-01-10',
      releaseDate: '2010-01-01',
      version: '19.5',
    },

    // Additional Reputation Apps
    {
      id: 'reviewpro',
      name: 'ReviewPro',
      slug: 'reviewpro',
      logo: '',
      shortDescription: 'Guest intelligence and reputation platform',
      fullDescription: 'ReviewPro helps hotels improve guest satisfaction through comprehensive review management and guest feedback analysis.',
      category: 'reputation',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.7,
      reviewCount: 289,
      installCount: 2200,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'ReviewPro (Shiji)', website: 'https://reviewpro.com', supportEmail: 'support@reviewpro.com' },
      features: ['Review aggregation', 'Surveys', 'Sentiment analysis', 'Benchmarking'],
      screenshots: [],
      integrationCapabilities: ['Multi-platform sync', 'PMS integration'],
      lastUpdated: '2025-01-12',
      releaseDate: '2012-01-01',
      version: '5.5.0',
    },
    {
      id: 'medallia',
      name: 'Medallia',
      slug: 'medallia',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Medallia_logo.svg/320px-Medallia_logo.svg.png',
      shortDescription: 'Enterprise experience management',
      fullDescription: 'Medallia provides enterprise-grade guest experience management with AI-powered insights and action recommendations.',
      category: 'reputation',
      pricing: 'custom',
      priceRange: '¥100,000 - ¥300,000/month',
      rating: 4.8,
      reviewCount: 178,
      installCount: 950,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: false,
      vendor: { name: 'Medallia', website: 'https://medallia.com', supportEmail: 'support@medallia.com' },
      features: ['Experience management', 'AI insights', 'Journey analytics', 'Action workflows'],
      screenshots: [],
      integrationCapabilities: ['Enterprise integration', 'API access'],
      lastUpdated: '2025-01-08',
      releaseDate: '2008-01-01',
      version: 'Enterprise',
    },

    // Additional Staff Management Apps
    {
      id: 'unifocus',
      name: 'UniFocus',
      slug: 'unifocus',
      logo: '',
      shortDescription: 'Labor management and workforce optimization',
      fullDescription: 'UniFocus provides comprehensive workforce management solutions for hotels including scheduling, time tracking, and labor forecasting.',
      category: 'staff_management',
      pricing: 'paid',
      priceRange: '¥40,000 - ¥100,000/month',
      rating: 4.5,
      reviewCount: 234,
      installCount: 1600,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'UniFocus', website: 'https://unifocus.com', supportEmail: 'support@unifocus.com' },
      features: ['Scheduling', 'Labor forecasting', 'Time tracking', 'Compliance'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Payroll sync'],
      lastUpdated: '2024-12-20',
      releaseDate: '2000-01-01',
      version: '8.0.0',
    },
    {
      id: 'hotelkit',
      name: 'hotelkit',
      slug: 'hotelkit',
      logo: '',
      shortDescription: 'Hotel collaboration and task management',
      fullDescription: 'hotelkit connects hotel teams through a collaboration platform with task management, checklists, and internal communication.',
      category: 'staff_management',
      pricing: 'paid',
      priceRange: '¥25,000 - ¥60,000/month',
      rating: 4.6,
      reviewCount: 178,
      installCount: 1100,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'hotelkit', website: 'https://hotelkit.net', supportEmail: 'support@hotelkit.net' },
      features: ['Team chat', 'Task management', 'Handover', 'Checklists'],
      screenshots: [],
      integrationCapabilities: ['PMS sync', 'Mobile app'],
      lastUpdated: '2025-01-05',
      releaseDate: '2014-01-01',
      version: '4.2.0',
    },

    // Additional Spa & Activities Apps
    {
      id: 'spasoft',
      name: 'SpaSoft',
      slug: 'spasoft',
      logo: '',
      shortDescription: 'Comprehensive spa management solution',
      fullDescription: 'SpaSoft provides spa and wellness centers with booking, resource management, and retail POS capabilities.',
      category: 'spa_activities',
      pricing: 'paid',
      priceRange: '¥50,000 - ¥130,000/month',
      rating: 4.5,
      reviewCount: 145,
      installCount: 850,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'SpaSoft (Springer-Miller)', website: 'https://spasoft.com', supportEmail: 'support@spasoft.com' },
      features: ['Booking', 'Resource scheduling', 'POS', 'Memberships'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Payment processing'],
      lastUpdated: '2024-11-15',
      releaseDate: '2002-01-01',
      version: '7.0.0',
    },
    {
      id: 'bokun',
      name: 'Bókun',
      slug: 'bokun',
      logo: '',
      shortDescription: 'Tours and activities booking platform',
      fullDescription: 'Bókun helps hotels sell tours, activities, and experiences through an easy-to-use booking platform with commission-free direct sales.',
      category: 'spa_activities',
      pricing: 'freemium',
      priceRange: 'Free + 1.5% commission',
      rating: 4.4,
      reviewCount: 234,
      installCount: 1400,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Bókun (TripAdvisor)', website: 'https://bokun.io', supportEmail: 'support@bokun.io' },
      features: ['Activity booking', 'Channel distribution', 'Inventory', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['Website widget', 'OTA connections'],
      lastUpdated: '2025-01-10',
      releaseDate: '2016-01-01',
      version: '3.8.0',
    },

    // Additional Parking Apps
    {
      id: 'parklio',
      name: 'Parklio',
      slug: 'parklio',
      logo: '',
      shortDescription: 'Smart parking management system',
      fullDescription: 'Parklio provides smart parking solutions for hotels including barriers, sensors, and a mobile app for guest parking.',
      category: 'parking',
      pricing: 'custom',
      priceRange: 'Contact for pricing',
      rating: 4.3,
      reviewCount: 89,
      installCount: 450,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: true,
      isPopular: false,
      vendor: { name: 'Parklio', website: 'https://parklio.com', supportEmail: 'info@parklio.com' },
      features: ['Smart barriers', 'Mobile access', 'Reservations', 'Analytics'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'IoT platform'],
      lastUpdated: '2024-12-01',
      releaseDate: '2019-01-01',
      version: '2.5.0',
    },
    {
      id: 'flashvalet',
      name: 'Flash Valet',
      slug: 'flashvalet',
      logo: '',
      shortDescription: 'Digital valet parking solution',
      fullDescription: 'Flash Valet modernizes hotel valet services with digital ticketing, vehicle tracking, and guest communication.',
      category: 'parking',
      pricing: 'paid',
      priceRange: '¥30,000 - ¥70,000/month',
      rating: 4.4,
      reviewCount: 123,
      installCount: 620,
      status: 'not_installed',
      integrationType: 'one_click',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: false,
      vendor: { name: 'Flash Parking', website: 'https://flashparking.com', supportEmail: 'support@flashparking.com' },
      features: ['Digital tickets', 'Vehicle tracking', 'Text notifications', 'Reporting'],
      screenshots: [],
      integrationCapabilities: ['PMS charge posting', 'Mobile app'],
      lastUpdated: '2024-10-20',
      releaseDate: '2017-01-01',
      version: '3.2.0',
    },

    // Additional In-Room Technology Apps
    {
      id: 'enseo',
      name: 'Enseo',
      slug: 'enseo',
      logo: '',
      shortDescription: 'In-room entertainment and connectivity',
      fullDescription: 'Enseo provides in-room entertainment solutions including streaming, casting, and interactive TV services for hotels.',
      category: 'in_room_tech',
      pricing: 'custom',
      priceRange: '¥5,000 - ¥15,000/room/year',
      rating: 4.5,
      reviewCount: 178,
      installCount: 1200,
      status: 'not_installed',
      integrationType: 'custom',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Enseo', website: 'https://enseo.com', supportEmail: 'support@enseo.com' },
      features: ['Streaming', 'Casting', 'Interactive TV', 'Guest messaging'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Content management'],
      lastUpdated: '2025-01-05',
      releaseDate: '2010-01-01',
      version: '5.0.0',
    },
    {
      id: 'volara',
      name: 'Volara',
      slug: 'volara',
      logo: '',
      shortDescription: 'Voice-enabled guest engagement',
      fullDescription: 'Volara provides voice-enabled solutions for hotels using Amazon Alexa, enabling guests to control their room and access hotel services.',
      category: 'in_room_tech',
      pricing: 'paid',
      priceRange: '¥3,000 - ¥8,000/room/year',
      rating: 4.6,
      reviewCount: 145,
      installCount: 850,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Volara', website: 'https://volara.io', supportEmail: 'support@volara.io' },
      features: ['Voice control', 'Room service', 'FAQ answers', 'Multi-language'],
      screenshots: [],
      integrationCapabilities: ['Alexa platform', 'PMS sync'],
      lastUpdated: '2024-12-10',
      releaseDate: '2018-01-01',
      version: '3.5.0',
    },
    {
      id: 'intelity',
      name: 'INTELITY',
      slug: 'intelity',
      logo: '',
      shortDescription: 'Comprehensive in-room technology platform',
      fullDescription: 'INTELITY offers a complete guest-facing technology platform including mobile app, in-room tablets, and smart room controls.',
      category: 'in_room_tech',
      pricing: 'custom',
      priceRange: '¥8,000 - ¥20,000/room/year',
      rating: 4.7,
      reviewCount: 234,
      installCount: 1500,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: true,
      isNew: false,
      isPopular: true,
      vendor: { name: 'INTELITY', website: 'https://intelity.com', supportEmail: 'info@intelity.com' },
      features: ['Guest app', 'In-room tablets', 'Smart controls', 'Service requests'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'IoT systems'],
      lastUpdated: '2025-01-15',
      releaseDate: '2012-01-01',
      version: '6.2.0',
    },

    // Additional Accounting Apps
    {
      id: 'aptech',
      name: 'Aptech PVNG',
      slug: 'aptech',
      logo: '',
      shortDescription: 'Enterprise hotel accounting software',
      fullDescription: 'Aptech PVNG is enterprise-grade accounting software designed specifically for the hospitality industry with multi-property support.',
      category: 'accounting',
      pricing: 'custom',
      priceRange: '¥80,000 - ¥200,000/month',
      rating: 4.4,
      reviewCount: 156,
      installCount: 980,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Aptech', website: 'https://aptech-inc.com', supportEmail: 'support@aptech-inc.com' },
      features: ['General ledger', 'Multi-property', 'Consolidation', 'Reporting'],
      screenshots: [],
      integrationCapabilities: ['PMS integration', 'Bank feeds'],
      lastUpdated: '2024-11-20',
      releaseDate: '1998-01-01',
      version: '10.0.0',
    },

    // Additional Security Apps
    {
      id: 'chargebacks911',
      name: 'Chargebacks911',
      slug: 'chargebacks911',
      logo: '',
      shortDescription: 'Chargeback prevention and management',
      fullDescription: 'Chargebacks911 helps hotels prevent and manage payment chargebacks through intelligent alerts and representment services.',
      category: 'security',
      pricing: 'paid',
      priceRange: 'Performance-based pricing',
      rating: 4.6,
      reviewCount: 189,
      installCount: 1100,
      status: 'not_installed',
      integrationType: 'api',
      isCertified: true,
      isFeatured: false,
      isNew: false,
      isPopular: true,
      vendor: { name: 'Chargebacks911', website: 'https://chargebacks911.com', supportEmail: 'support@chargebacks911.com' },
      features: ['Alert management', 'Representment', 'Analytics', 'Prevention'],
      screenshots: [],
      integrationCapabilities: ['Payment processor integration', 'PMS sync'],
      lastUpdated: '2024-12-15',
      releaseDate: '2011-01-01',
      version: '5.0.0',
    },
  ];

  return apps;
};

// Generate AI insights based on installed apps and property profile
const generateInsights = (apps: MarketplaceApp[]): MarketplaceInsight[] => {
  const installedApps = apps.filter(a => a.status === 'installed');
  const insights: MarketplaceInsight[] = [];

  // Check for missing critical integrations
  const hasRMS = installedApps.some(a => a.category === 'revenue_management');
  const hasUpselling = installedApps.some(a => a.category === 'upselling');
  const hasReputation = installedApps.some(a => a.category === 'reputation');
  const hasHousekeeping = installedApps.some(a => a.category === 'housekeeping');

  if (!hasUpselling) {
    insights.push({
      id: 'missing-upselling',
      type: 'recommendation',
      priority: 'high',
      title: 'Boost Revenue with Upselling',
      description: 'Properties using upselling tools see 8-15% revenue increase. Based on your profile, Oaky would be an excellent fit.',
      action: 'Explore Oaky - top-rated upselling platform with proven ROI',
      relatedAppId: 'oaky',
      relatedCategory: 'upselling',
      potentialImpact: '¥2.4M additional annual revenue',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  if (!hasReputation) {
    insights.push({
      id: 'missing-reputation',
      type: 'recommendation',
      priority: 'medium',
      title: 'Improve Guest Satisfaction Tracking',
      description: 'You\'re not monitoring online reviews systematically. TrustYou can aggregate reviews and provide actionable insights.',
      action: 'Connect TrustYou for comprehensive reputation management',
      relatedAppId: 'trustyou',
      relatedCategory: 'reputation',
      potentialImpact: '+0.3 average rating improvement',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  if (!hasHousekeeping) {
    insights.push({
      id: 'missing-housekeeping',
      type: 'opportunity',
      priority: 'medium',
      title: 'Optimize Housekeeping Operations',
      description: 'AI-powered housekeeping tools reduce labor costs by 15-20% while improving room turnover times.',
      action: 'Evaluate Optii Solutions for intelligent room assignment',
      relatedAppId: 'optii',
      relatedCategory: 'housekeeping',
      potentialImpact: '¥1.8M annual labor savings',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  // Check for integration health
  const unhealthyApps = installedApps.filter(a => a.healthStatus === 'error' || a.healthStatus === 'warning');
  if (unhealthyApps.length > 0) {
    insights.push({
      id: 'integration-health',
      type: 'alert',
      priority: 'high',
      title: `${unhealthyApps.length} Integration${unhealthyApps.length > 1 ? 's' : ''} Need Attention`,
      description: `Some integrations are experiencing issues that may affect operations: ${unhealthyApps.map(a => a.name).join(', ')}`,
      action: 'Review integration status and contact support if needed',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  // Cost optimization
  const totalSpend = installedApps.reduce((sum, a) => sum + (a.monthlySpend || 0), 0);
  if (totalSpend > 500000) {
    insights.push({
      id: 'cost-optimization',
      type: 'optimization',
      priority: 'low',
      title: 'Marketplace Spend Optimization',
      description: `Your monthly marketplace spend is ¥${totalSpend.toLocaleString()}. Consider bundled pricing or annual contracts for savings.`,
      action: 'Contact vendors about volume discounts or annual pricing',
      potentialImpact: '10-20% cost reduction possible',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  // Trending recommendation
  insights.push({
    id: 'trending-ai',
    type: 'trend',
    priority: 'low',
    title: 'AI Guest Messaging is Trending',
    description: '70% of guest queries can be handled by AI chatbots. Akia is seeing rapid adoption with excellent reviews.',
    action: 'Explore AI-powered guest messaging solutions',
    relatedAppId: 'akia',
    relatedCategory: 'guest_messaging',
    createdAt: new Date().toISOString(),
    dismissed: false,
  });

  // New app recommendation
  const canaryApp = apps.find(a => a.id === 'canary');
  if (canaryApp && canaryApp.status === 'not_installed') {
    insights.push({
      id: 'contactless-checkin',
      type: 'recommendation',
      priority: 'medium',
      title: 'Enhance Contactless Experience',
      description: 'Mobile check-in adoption has surged 300% since 2020. Canary Technologies offers industry-leading digital check-in with fraud prevention.',
      action: 'Schedule a demo with Canary Technologies',
      relatedAppId: 'canary',
      relatedCategory: 'guest_experience',
      potentialImpact: '60% reduction in check-in time',
      createdAt: new Date().toISOString(),
      dismissed: false,
    });
  }

  return insights;
};

const initialApps = generateApps();
const initialCategories = getCategoriesWithCounts(initialApps);

export const useMarketplaceStore = create<MarketplaceState>((set, get) => ({
  apps: initialApps,
  categories: initialCategories,
  insights: generateInsights(initialApps),

  selectedCategory: 'all',
  searchQuery: '',
  sortBy: 'popular',
  filterStatus: 'all',
  filterPricing: 'all',

  totalInstalled: initialApps.filter(a => a.status === 'installed').length,
  totalMonthlySpend: initialApps.filter(a => a.status === 'installed').reduce((sum, a) => sum + (a.monthlySpend || 0), 0),
  totalApiCalls: initialApps.filter(a => a.status === 'installed').reduce((sum, a) => sum + (a.apiCalls || 0), 0),

  setSelectedCategory: (category) => set({ selectedCategory: category }),
  setSearchQuery: (query) => set({ searchQuery: query }),
  setSortBy: (sort) => set({ sortBy: sort }),
  setFilterStatus: (status) => set({ filterStatus: status }),
  setFilterPricing: (pricing) => set({ filterPricing: pricing }),

  installApp: (appId) => set((state) => {
    const apps = state.apps.map(app =>
      app.id === appId
        ? { ...app, status: 'installed' as AppStatus, installedAt: new Date().toISOString(), healthStatus: 'healthy' as const }
        : app
    );
    return {
      apps,
      totalInstalled: apps.filter(a => a.status === 'installed').length,
      insights: generateInsights(apps),
    };
  }),

  uninstallApp: (appId) => set((state) => {
    const apps = state.apps.map(app =>
      app.id === appId
        ? { ...app, status: 'not_installed' as AppStatus, installedAt: undefined, healthStatus: undefined }
        : app
    );
    return {
      apps,
      totalInstalled: apps.filter(a => a.status === 'installed').length,
      totalMonthlySpend: apps.filter(a => a.status === 'installed').reduce((sum, a) => sum + (a.monthlySpend || 0), 0),
      insights: generateInsights(apps),
    };
  }),

  dismissInsight: (insightId) => set((state) => ({
    insights: state.insights.map(i => i.id === insightId ? { ...i, dismissed: true } : i),
  })),
}));
