import { GuestService, ServiceCategory } from '@/types/guest';

export const mockServices: GuestService[] = [
  // Spa & Wellness
  {
    id: 'spa-1',
    name: 'Private Onsen Experience',
    nameJa: 'プライベート温泉',
    description: 'Exclusive 60-minute private hot spring bath with mountain views',
    descriptionJa: '山の景色を眺めながらの60分プライベート温泉',
    category: 'spa',
    price: 8000,
    currency: 'JPY',
    duration: 60,
    rating: 4.9,
    reviewCount: 127,
    popular: true,
    available: true,
    icon: 'Waves',
  },
  {
    id: 'spa-2',
    name: 'Traditional Shiatsu Massage',
    nameJa: '指圧マッサージ',
    description: 'Authentic Japanese pressure-point massage therapy',
    descriptionJa: '本格的な日本式指圧マッサージ',
    category: 'spa',
    price: 15000,
    currency: 'JPY',
    duration: 90,
    rating: 4.8,
    reviewCount: 89,
    popular: true,
    available: true,
    icon: 'Sparkles',
  },
  {
    id: 'spa-3',
    name: 'Aromatherapy Facial',
    nameJa: 'アロマフェイシャル',
    description: 'Relaxing facial with local botanical ingredients',
    descriptionJa: '地元の植物成分を使用したリラックスフェイシャル',
    category: 'spa',
    price: 12000,
    currency: 'JPY',
    duration: 60,
    rating: 4.7,
    reviewCount: 45,
    popular: false,
    available: true,
    icon: 'Flower2',
  },

  // Restaurant
  {
    id: 'rest-1',
    name: 'Hokki & Scallop Don',
    nameJa: 'ホッキ貝とホタテ丼',
    description: 'Local Hokkaido specialty · Limited',
    descriptionJa: '北海道産地元の逸品・数量限定',
    category: 'restaurant',
    price: 2300,
    currency: 'JPY',
    rating: 4.9,
    reviewCount: 127,
    popular: true,
    available: true,
    icon: 'Fish',
    image: '/menu/pickled-cabbage-fish.jpg',
    isChefRecommendation: true,
    status: 'fresh',
    tags: ['Seafood', 'Local'],
  },
  {
    id: 'rest-2',
    name: 'Wagyu Beef Bowl',
    nameJa: '和牛丼',
    description: 'A5 Hokkaido wagyu · Signature dish',
    descriptionJa: '北海道産A5和牛・看板メニュー',
    category: 'restaurant',
    price: 4500,
    currency: 'JPY',
    rating: 4.9,
    reviewCount: 203,
    popular: true,
    available: true,
    icon: 'UtensilsCrossed',
    image: '/menu/sichuan-boiled-wagyu-beef.jpg',
    isChefRecommendation: true,
    status: 'signature',
    tags: ['Wagyu', 'Premium'],
  },
  {
    id: 'rest-3',
    name: 'Sushi Omakase',
    nameJa: '寿司おまかせ',
    description: "Chef's selection of seasonal sushi",
    descriptionJa: 'シェフ厳選の季節の寿司',
    category: 'restaurant',
    price: 18000,
    currency: 'JPY',
    duration: 90,
    rating: 4.8,
    reviewCount: 156,
    popular: true,
    available: true,
    icon: 'Fish',
    image: '/sushi-platter.png',
    isChefRecommendation: true,
    status: 'seasonal',
    tags: ['Sushi', 'Omakase'],
  },
  {
    id: 'rest-4',
    name: 'Miso Ramen',
    nameJa: '味噌ラーメン',
    description: 'Hokkaido-style rich miso broth',
    descriptionJa: '北海道風濃厚味噌スープ',
    category: 'restaurant',
    price: 1400,
    currency: 'JPY',
    rating: 4.7,
    reviewCount: 312,
    popular: true,
    available: true,
    icon: 'Soup',
    image: '/menu/silky-pork-soup.jpg',
    status: 'fresh',
    tags: ['Ramen', 'Local'],
  },
  {
    id: 'rest-5',
    name: 'Grilled Corn Croquette',
    nameJa: 'とうもろこしコロッケ',
    description: 'Niseko farm fresh corn',
    descriptionJa: 'ニセコ産新鮮とうもろこし',
    category: 'restaurant',
    price: 850,
    currency: 'JPY',
    rating: 4.6,
    reviewCount: 89,
    popular: false,
    available: true,
    icon: 'Cookie',
    image: '/menu/crispy-corn-cake.jpg',
    status: 'seasonal',
    tags: ['Appetizer', 'Vegetarian'],
  },
  {
    id: 'rest-6',
    name: 'Sake Tasting Set',
    nameJa: '日本酒テイスティングセット',
    description: 'Premium local sake · 5 varieties',
    descriptionJa: '厳選された地酒5種のテイスティング',
    category: 'restaurant',
    price: 3500,
    currency: 'JPY',
    rating: 4.7,
    reviewCount: 78,
    popular: false,
    available: true,
    icon: 'Wine',
    image: '/products/whisky-yoichi.jpg',
    isChefRecommendation: true,
    status: 'limited',
    tags: ['Drinks', 'Premium'],
  },

  // Activities
  {
    id: 'act-1',
    name: 'Private Ski Lesson',
    nameJa: 'プライベートスキーレッスン',
    description: 'One-on-one instruction at Grand Hirafu with certified instructor',
    descriptionJa: '公認インストラクターによるグランヒラフでのマンツーマンレッスン',
    category: 'activities',
    price: 35000,
    currency: 'JPY',
    duration: 180,
    rating: 4.9,
    reviewCount: 312,
    popular: true,
    available: true,
    icon: 'Snowflake',
  },
  {
    id: 'act-2',
    name: 'Snowshoe Forest Trek',
    nameJa: 'スノーシュー森林トレッキング',
    description: 'Guided walk through pristine Niseko forests',
    descriptionJa: 'ニセコの原生林をガイドと歩くスノーシューツアー',
    category: 'activities',
    price: 12000,
    currency: 'JPY',
    duration: 150,
    rating: 4.8,
    reviewCount: 89,
    popular: true,
    available: true,
    icon: 'TreePine',
  },
  {
    id: 'act-3',
    name: 'Mt. Yotei Sunrise Tour',
    nameJa: '羊蹄山サンライズツアー',
    description: 'Early morning tour with stunning views of iconic Mt. Yotei',
    descriptionJa: '羊蹄山の絶景を望む早朝ツアー',
    category: 'activities',
    price: 15000,
    currency: 'JPY',
    duration: 180,
    rating: 4.9,
    reviewCount: 67,
    popular: false,
    available: true,
    icon: 'Mountain',
  },

  // Transport
  {
    id: 'trans-1',
    name: 'Airport Transfer (New Chitose)',
    nameJa: '空港送迎（新千歳）',
    description: 'Private luxury vehicle transfer from New Chitose Airport',
    descriptionJa: '新千歳空港からの専用車送迎',
    category: 'transport',
    price: 45000,
    currency: 'JPY',
    duration: 150,
    rating: 4.9,
    reviewCount: 234,
    popular: true,
    available: true,
    icon: 'Plane',
  },
  {
    id: 'trans-2',
    name: 'Ski Resort Shuttle',
    nameJa: 'スキー場シャトル',
    description: 'Complimentary shuttle to all Niseko United resorts',
    descriptionJa: 'ニセコユナイテッド全リゾートへの無料シャトル',
    category: 'transport',
    price: 0,
    currency: 'JPY',
    rating: 4.7,
    reviewCount: 456,
    popular: true,
    available: true,
    icon: 'Bus',
  },
  {
    id: 'trans-3',
    name: 'Village Tour (Private Car)',
    nameJa: '村内ツアー（専用車）',
    description: 'Explore Niseko village with your own driver',
    descriptionJa: '専属ドライバーでニセコ村を散策',
    category: 'transport',
    price: 20000,
    currency: 'JPY',
    duration: 180,
    rating: 4.6,
    reviewCount: 34,
    popular: false,
    available: true,
    icon: 'Car',
  },

  // Room Service
  {
    id: 'room-1',
    name: 'In-Room Breakfast',
    nameJa: 'ルームサービス朝食',
    description: 'Japanese or Western breakfast delivered to your room',
    descriptionJa: '和食または洋食の朝食をお部屋にお届け',
    category: 'room_service',
    price: 4500,
    currency: 'JPY',
    rating: 4.8,
    reviewCount: 189,
    popular: true,
    available: true,
    icon: 'Coffee',
  },
  {
    id: 'room-2',
    name: 'Late Night Ramen',
    nameJa: '深夜ラーメン',
    description: 'Warm, comforting ramen after a day on the slopes',
    descriptionJa: 'スキー後の温かいラーメン',
    category: 'room_service',
    price: 2200,
    currency: 'JPY',
    rating: 4.7,
    reviewCount: 267,
    popular: true,
    available: true,
    icon: 'Soup',
  },
  {
    id: 'room-3',
    name: 'Champagne & Chocolates',
    nameJa: 'シャンパン＆チョコレート',
    description: 'Premium champagne with artisan chocolates',
    descriptionJa: 'プレミアムシャンパンとアルチザンチョコレート',
    category: 'room_service',
    price: 18000,
    currency: 'JPY',
    rating: 4.9,
    reviewCount: 45,
    popular: false,
    available: true,
    icon: 'Sparkles',
  },
];

export const serviceCategories: { key: ServiceCategory; label: string; labelJa: string; icon: string }[] = [
  { key: 'spa', label: 'Spa & Wellness', labelJa: 'スパ＆ウェルネス', icon: 'Waves' },
  { key: 'restaurant', label: 'Restaurant', labelJa: 'レストラン', icon: 'UtensilsCrossed' },
  { key: 'activities', label: 'Activities', labelJa: 'アクティビティ', icon: 'Snowflake' },
  { key: 'transport', label: 'Transport', labelJa: '送迎', icon: 'Car' },
  { key: 'room_service', label: 'Room Service', labelJa: 'ルームサービス', icon: 'Coffee' },
];

export function getServicesByCategory(category: ServiceCategory): GuestService[] {
  return mockServices.filter(s => s.category === category);
}

export function getPopularServices(): GuestService[] {
  return mockServices.filter(s => s.popular);
}

export function getServiceById(id: string): GuestService | undefined {
  return mockServices.find(s => s.id === id);
}
